In [1]:
import h5py
import os
import numpy as np

In [2]:
type_file = 'test'

name = f'./all_vox256_img_with_classes/all_vox256_img_{type_file}.hdf5'
txt_path = f'./all_vox256_img_with_classes/all_vox256_img_{type_file}.txt'

hdf5_file = h5py.File(name, 'a')
obj_paths = [line.rstrip('\n') for line in open(txt_path, mode='r').readlines()]
num_elements = hdf5_file['voxels'].shape[0]
assert num_elements == len(obj_paths)

classes_names = list(set(map(lambda x: x.split(os.sep)[0], obj_paths)))
classes_names = list(sorted(classes_names))
indx2class = map(lambda x: classes_names.index(x.split(os.sep)[0]), obj_paths)
indx2class = np.array(list(indx2class), dtype=np.uint8).reshape((-1,))

In [3]:
np.unique(indx2class, return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=uint8),
 array([ 809,  364,  315, 1500, 1356,  219,  464,  324,  475,  635, 1702,
         211,  388]))

In [4]:
hdf5_file.create_dataset("classes", [num_elements], np.uint8, compression=9)
hdf5_file['classes'][:] = indx2class[:]

In [5]:
hdf5_file.close()

### Test

In [3]:
type_file = 'test'

name = f'./all_vox256_img_with_classes/all_vox256_img_{type_file}.hdf5'
txt_path = f'./all_vox256_img_with_classes/all_vox256_img_{type_file}.txt'

hdf5_file = h5py.File(name, 'r')
obj_paths = [line.rstrip('\n') for line in open(txt_path, mode='r').readlines()]
num_elements = hdf5_file['voxels'].shape[0]
assert num_elements == len(obj_paths)

classes_names = list(set(map(lambda x: x.split(os.sep)[0], obj_paths)))
classes_names = list(sorted(classes_names))
indx2class = map(lambda x: classes_names.index(x.split(os.sep)[0]), obj_paths)
indx2class = np.array(list(indx2class), dtype=np.uint8).reshape((-1,))

In [7]:
hdf5_file['classes'][5023:5030], indx2class[5023:5030]

(array([6, 6, 6, 6, 7, 7, 7], dtype=uint8),
 array([6, 6, 6, 6, 7, 7, 7], dtype=uint8))

In [8]:
obj_paths[5023:5030]

['03636649/ff43ef647c75b5a4fcb8d8c6d4df8143',
 '03636649/ffc2479f27a1013afcec439ba0368db0',
 '03636649/ffc3e351b9ae77b0d42b9650f19dd425',
 '03636649/fff6acd5b543ae02a9bdc22a1e02e82',
 '03691459/c90cbb0458648665da49a3feeb6532eb',
 '03691459/c91e878553979be9c5c378bd9e63485',
 '03691459/c91f926711d5e8261d485f425cc21556']

In [12]:
a = (1,2,3)

In [13]:
(*a, 10)

(1, 2, 3, 10)